=== Luka147m/OR-labos/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "title": "OR gradovi",
    "description": "Labos iz predmeta Otvoreno Računarstvo\nSkup podataka o gradovima Hrvatske",
    "type": "array",
    "default": [],
    "items": {
        "title": "Grad",
        "description": "Objekt koji sadrži sve podatke o gradu",
        "type": "object",
        "required": [
            "gradid",
            "imegrada",
            "zupanija",
            "gradonacelnik",
            "brojstanovnika",
            "povrsina",
            "godinaosnutka",
            "latitude",
            "longitude",
            "nadmorskavisina",
            "kvartovi"
        ],
        "properties": {
            "gradid": {
                "title": "gradid",
                "description": "ID grada",
                "type": "integer"
            },
            "imegrada": {
                "title": "imegrada",
                "description": "Sadrži ime grada",
                "type": "string"
            },
            "zupanija": {
                "title": "zupanija",
                "description": "Županija u kojoj se nalazi grad",
                "type": "string"
            },
            "gradonacelnik": {
                "title": "gradonacelnik",
                "description": "Trenutni gradonačelnik",
                "type": "string"
            },
            "brojstanovnika": {
                "title": "brojstanovnika",
                "description": "Broj stanovnika pojedinog grada",
                "type": "integer"
            },
            "povrsina": {
                "title": "povrsina",
                "description": "Površina pod vlasništvom grada (u kilometrima kvadratnim)",
                "type": "number"
            },
            "godinaosnutka": {
                "title": "godinaosnutka",
                "description": "Godina kada je grad osnovan (negativna godina predstavlja godinu prije krista)",
                "type": "integer"
            },
            "latitude": {
                "title": "latitude",
                "description": "Zemljopisna širina grada",
                "type": "number"
            },
            "longitude": {
                "title": "longitude",
                "description": "Zemljopisna visina grada",
                "type": "number"
            },
            "nadmorskavisina": {
                "title": "nadmorskavisina",
                "description": "Nadmorska visina na kojoj se nalazi grad",
                "type": "integer"
            },
            "kvartovi": {
                "title": "kvartovi",
                "description": "Popis kvartova grada",
                "type": "array",
                "items": {
                    "title": "Kvart",
                    "description": "Objekt koji sadrži informacije o kvartu",
                    "type": "object",
                    "required": [
                        "nazivkvarta",
                        "brojkvartstan"
                    ],
                    "properties": {
                        "nazivkvarta": {
                            "title": "nazivkvarta",
                            "description": "Naziv kvarta",
                            "type": "string"
                        },
                        "brojkvartstan": {
                            "title": "brojkvartstan",
                            "description": "Broj stanovnika u pojedinom kvartu",
                            "type": "integer"
                        }
                    }
                }
            }
        }
    }
}

=== Luka147m/OR-labos/Gradovi.json
[
  {
    "gradid": 1,
    "imegrada": "Zagreb",
    "zupanija": "Grad Zagreb",
    "gradonacelnik": "Tomislav Tomašević",
    "brojstanovnika": 790017,
    "povrsina": 641.0,
    "godinaosnutka": 1850,
    "latitude": 45.815,
    "longitude": 15.9819,
    "nadmorskavisina": 122,
    "kvartovi": [
      {
        "nazivkvarta": "Donji Grad",
        "brojkvartstan": 45000
      },
      {
        "nazivkvarta": "Trešnjevka",
        "brojkvartstan": 65000
      },
      {
        "nazivkvarta": "Novi Zagreb",
        "brojkvartstan": 70000
      }
    ]
  },
  {
    "gradid": 2,
    "imegrada": "Split",
    "zupanija": "Splitsko-dalmatinska",
    "gradonacelnik": "Ivo Baldasar",
    "brojstanovnika": 178192,
    "povrsina": 79.0,
    "godinaosnutka": 295,
    "latitude": 43.5081,
    "longitude": 16.4402,
    "nadmorskavisina": 0,
    "kvartovi": [
      {
        "nazivkvarta": "Split-Centar",
        "brojkvartstan": 25000
      },
      {
        "nazivkvarta": "Split-Sjever",
        "brojkvartstan": 35000
      },
      {
        "nazivkvarta": "Split-Jug",
        "brojkvartstan": 45000
      }
    ]
  },
  {
    "gradid": 10,
    "imegrada": "Vukovar",
    "zupanija": "Vukovarsko-srijemska",
    "gradonacelnik": "Ivan Penava",
    "brojstanovnika": 27711,
    "povrsina": 74.0,
    "godinaosnutka": 1232,
    "latitude": 45.3464,
    "longitude": 18.9954,
    "nadmorskavisina": 91,
    "kvartovi": []
  },
  {
    "gradid": 5,
    "imegrada": "Zadar",
    "zupanija": "Zadarska",
    "gradonacelnik": "Branko Dukić",
    "brojstanovnika": 75088,
    "povrsina": 194.0,
    "godinaosnutka": 9,
    "latitude": 44.1194,
    "longitude": 15.2314,
    "nadmorskavisina": 0,
    "kvartovi": []
  },
  {
    "gradid": 8,
    "imegrada": "Varaždin",
    "zupanija": "Varaždinska",
    "gradonacelnik": "Ivan Čehok",
    "brojstanovnika": 46498,
    "povrsina": 63.0,
    "godinaosnutka": 1181,
    "latitude": 46.3038,
    "longitude": 16.3375,
    "nadmorskavisina": 177,
    "kvartovi": []
  },
  {
    "gradid": 6,
    "imegrada": "Pula",
    "zupanija": "Istarska",
    "gradonacelnik": "Filip Zoričić",
    "brojstanovnika": 57833,
    "povrsina": 51.0,
    "godinaosnutka": 177,
    "latitude": 44.8666,
    "longitude": 13.8496,
    "nadmorskavisina": 20,
    "kvartovi": []
  },
  {
    "gradid": 4,
    "imegrada": "Osijek",
    "zupanija": "Osječko-baranjska",
    "gradonacelnik": "Ivan Vrkić",
    "brojstanovnika": 108048,
    "povrsina": 171.0,
    "godinaosnutka": 1687,
    "latitude": 45.5511,
    "longitude": 18.6932,
    "nadmorskavisina": 90,
    "kvartovi": []
  },
  {
    "gradid": 3,
    "imegrada": "Rijeka",
    "zupanija": "Primorsko-goranska",
    "gradonacelnik": "Marko Filipović",
    "brojstanovnika": 128384,
    "povrsina": 44.0,
    "godinaosnutka": 1288,
    "latitude": 45.3271,
    "longitude": 14.4422,
    "nadmorskavisina": 0,
    "kvartovi": []
  },
  {
    "gradid": 9,
    "imegrada": "Šibenik",
    "zupanija": "Šibensko-kninska",
    "gradonacelnik": "Željko Burić",
    "brojstanovnika": 34368,
    "povrsina": 51.0,
    "godinaosnutka": 1066,
    "latitude": 43.7357,
    "longitude": 15.8895,
    "nadmorskavisina": 0,
    "kvartovi": []
  },
  {
    "gradid": 7,
    "imegrada": "Dubrovnik",
    "zupanija": "Dubrovačko-neretvanska",
    "gradonacelnik": "Mato Franković",
    "brojstanovnika": 42890,
    "povrsina": 21.0,
    "godinaosnutka": 7,
    "latitude": 42.6507,
    "longitude": 18.0944,
    "nadmorskavisina": 0,
    "kvartovi": []
  }
]
